services:
  mail:
    container_name: "sendgrid-smtp-relay"
    build: .
    ports:
      # Don't bind to 0.0.0.0 unless you have a properly setup firewall.
      # This service has no authentication!
      - "127.0.0.1:25:25"
    environment:
      - SENDGRID_API_KEY=
      # - DOMAIN_FROM_ALLOWLIST=
      # - DOMAIN_TO_ALLOWLIST=